spring:
  #application:
    #name: shiro
  redis:
    sentinel:
      master: redis-sentinel
      nodes: 192.168.13.63:26382,192.168.13.62:26382
    password: abcd_123456


server:
     port: 8090
     
